#!/usr/bin/env python3
"""Grub Pilot - Translations DE / EN"""

TRANSLATIONS = {
    'de': {
        'app_title':         'Grub Pilot',
        'nav_home':          '🏠  Start',
        'nav_entries':       '📋  Boot-Einträge',
        'nav_timeout':       '⏱️   Timeout',
        'nav_themes':        '🎨  Themes',
        'nav_backups':       '💾  Backups',
        'nav_settings':      '⚙️   Einstellungen',
        'nav_help':          '❓  Hilfe',
        'nav_about':         'ℹ️   Über',
        'home_subtitle':     'Sicheres GRUB-Konfigurationswerkzeug',
        'entries_title':     '📋 Boot-Einträge',
        'entries_empty':     'Keine Boot-Einträge gefunden.',
        'entries_set_def':   'Als Standard',
        'timeout_title':     '⏱️ Boot-Timeout',
        'timeout_disabled':  'Deaktiviert',
        'timeout_instant':   'Sofort',
        'timeout_sec':       '{n} Sekunden',
        'timeout_hint':      '-1 = kein Menü  |  0 = sofort  |  1–30 = Sekunden',
        'timeout_save':      '💾  Speichern',
        'themes_title':      '🎨 GRUB-Themes',
        'themes_empty':      'Keine Themes installiert.',
        'themes_hint':       'Themes werden in /boot/grub/themes/ installiert.',
        'themes_activate':   'Aktivieren',
        'backups_title':     '💾 Backups',
        'backups_empty':     'Keine Backups vorhanden.',
        'backups_restore':   '↩  Wiederherstellen',
        'backups_confirm':   'Backup wirklich wiederherstellen?\nDas System wird neu konfiguriert.',
        'settings_title':    '⚙️ Einstellungen',
        'settings_lang':     'Sprache / Language',
        'settings_appear':   'Erscheinungsbild',
        'settings_dark':     'Dunkel',
        'settings_light':    'Hell',
        'settings_save':     '💾  Einstellungen speichern',
        'help_title':        '❓ Hilfe & Dokumentation',
        'about_title':       'ℹ️ Über Grub Pilot',
        'about_author':      'Autor',
        'about_location':    'Ort',
        'about_email':       'E-Mail',
        'about_license':     'Lizenz',
        'about_version':     'Version',
        'about_disclaimer':  ('⚠️ Haftungsausschluss\n\n'
                              'Dieses Programm wird ohne jegliche Gewährleistung bereitgestellt. '
                              'Änderungen am Bootloader können das System unbrauchbar machen. '
                              'Der Autor übernimmt keine Haftung für Datenverlust oder Systemschäden. '
                              'Benutzung auf eigene Gefahr.'),
        'about_thirdparty':  ('Verwendete Drittanbieter-Software:\n'
                              '• customtkinter (MIT-Lizenz)\n'
                              '  https://github.com/TomSchimansky/CustomTkinter\n'
                              '• dbus-python (LGPL-2.1)\n'
                              '  https://pypi.org/project/dbus-python/\n'
                              '• PyGObject (LGPL-2.1)\n'
                              '  https://pygobject.readthedocs.io/'),
        # Navigation
        'nav_section_main':  'KONFIGURATION',
        'nav_section_tools': 'WERKZEUGE',
        'nav_kernel':        '⚙️   Kernel-Parameter',
        'nav_wallpaper':     '🖼️   Hintergrundbild',
        'nav_display':       '🖥️   Anzeige / Video',
        'nav_efi':           '🔒  EFI-Reihenfolge',
        'nav_custom':        '📝  Eigene Einträge',
        'nav_profiles':      '📤  Profile',
        'nav_logs':          '📄  Live-Log',
        'nav_repair':        '🔧  Reparatur',
        # Kernel
        'kernel_title':      '⚙️ Kernel-Parameter',
        'kernel_current':    'Aktueller Wert (GRUB_CMDLINE_LINUX_DEFAULT)',
        'kernel_toggles':    'Schnell-Toggles',
        'kernel_save':       '💾  Parameter speichern',
        'kernel_saved':      '✅ Kernel-Parameter gespeichert',
        # Repair
        'repair_title':      '🔧 GRUB Reparatur',
        'repair_select_disk':'Laufwerk auswählen',
        'repair_refresh':    'Aktualisieren',
        'repair_actions':    'Aktionen',
        'repair_install':    'GRUB installieren',
        'repair_update':     'GRUB aktualisieren',
        'repair_warning':    '⚠️  Achtung: grub-install schreibt den Bootloader auf das gewählte Laufwerk. Stellen Sie sicher, dass Sie das richtige Laufwerk ausgewählt haben!',
        'repair_output':     'Ausgabe:',
        'repair_install_ok': '✅ GRUB erfolgreich installiert',
        'repair_update_ok':  '✅ GRUB erfolgreich aktualisiert',
        'repair_no_disk':    '⚠️ Bitte ein Laufwerk auswählen',
        # Wallpaper
        'wallpaper_title':    '🖼️ Hintergrundbild',
        'wallpaper_select':   'Bild auswählen',
        'wallpaper_path_hint':'Pfad zum Bild (PNG, JPG, TGA…)',
        'wallpaper_browse':   '📂  Datei auswählen…',
        'wallpaper_formats':  'Unterstützte Formate: PNG, JPG, TGA, BMP',
        'wallpaper_no_preview':'Kein Bild ausgewählt',
        'wallpaper_set':      '💾  Bild setzen',
        'wallpaper_remove':   '🗑  Entfernen',
        'wallpaper_set_ok':   '✅ Hintergrundbild gesetzt',
        'wallpaper_removed':  '✅ Hintergrundbild entfernt',
        'wallpaper_no_file':  '⚠️ Bitte zuerst eine Datei auswählen',
        # Display
        'display_title':          '🖥️ Anzeige / Video-Modus',
        'display_gfxmode':        'Auflösung des GRUB-Menüs',
        'display_gfxmode_hint':   'Empfohlen: auto oder 1920x1080',
        'display_payload':        'Video-Modus nach dem Booten',
        'display_payload_text':   'Textmodus',
        'display_payload_keep':   'Auflösung beibehalten',
        'display_payload_auto':   'Automatisch',
        'display_payload_hint':   'keep = GRUB-Auflösung wird an den Kernel übergeben',
        'display_osprober':       'os-prober (Dual-Boot-Erkennung)',
        'display_osprober_hint':  'Aktivieren für Dual-Boot mit Windows / anderen OS',
        'display_osprober_on':    'Aktiviert',
        'display_save':           '💾  Einstellungen speichern',
        'display_saved':          '✅ Anzeige-Einstellungen gespeichert',
        # EFI
        'efi_title':       '🔒 EFI Boot-Reihenfolge',
        'efi_refresh':     'Aktualisieren',
        'efi_up':          'Hoch',
        'efi_down':        'Runter',
        'efi_delete':      'Löschen',
        'efi_save_order':  '💾  Reihenfolge speichern',
        'efi_no_uefi':     'Dieses System verwendet kein UEFI. Die EFI-Reihenfolge ist nur auf UEFI-Systemen verfügbar.',
        'efi_empty':       'Keine EFI-Einträge gefunden.',
        'efi_deleted':     '✅ EFI-Eintrag gelöscht',
        'efi_order_saved': '✅ EFI-Reihenfolge gespeichert',
        # Custom Entries
        'custom_title':              '📝 Eigene Boot-Einträge',
        'custom_hint':               'Bearbeiten Sie /etc/grub.d/40_custom direkt. Nach dem Speichern wird GRUB automatisch aktualisiert.',
        'custom_template':           '📄 Vorlage einfügen',
        'custom_reload':             'Neu laden',
        'custom_save':               '💾  Speichern & GRUB aktualisieren',
        'custom_saved':              '✅ Einträge gespeichert',
        'custom_reloaded':           '✅ Neu geladen',
        'custom_empty_placeholder':  '# Eigene GRUB-Einträge hier einfügen\n# Nutzen Sie die Vorlage-Schaltfläche als Ausgangspunkt.\n',
        # Profiles
        'profiles_title':        '📤 Konfigurations-Profile',
        'profiles_export_title': 'Konfiguration exportieren',
        'profiles_export_hint':  'Aktuelle GRUB-Einstellungen als JSON-Profil speichern',
        'profiles_export_btn':   'Profil exportieren',
        'profiles_import_title': 'Konfiguration importieren',
        'profiles_import_hint':  'Gespeichertes Profil laden und anwenden',
        'profiles_import_btn':   'Profil importieren',
        'profiles_current':      'Aktuelle Konfiguration (Vorschau)',
        'profiles_export_empty': '⚠️ Keine Konfiguration gefunden',
        'profiles_export_ok':    '✅ Profil exportiert: {path}',
        'profiles_import_ok':    '✅ Profil importiert und GRUB aktualisiert',
        # Logs
        'logs_title':    '📄 Live Log-Viewer',
        'logs_live_on':  'Live starten',
        'logs_live_off': 'Live stoppen',
        'logs_clear':    'Leeren',
        'logs_export':   'Exportieren',
        'logs_filter':   'Filter:',
        'themes_install_btn':   '📦  Theme installieren (.tar.xz)',
        'themes_install_title':  '📦 Theme aus Archiv installieren',
        'themes_install_hint':   'GRUB-Theme-Archiv auswählen (.tar.xz)',
        'themes_install_select': 'Datei auswählen…',
        'themes_install_path':   'Pfad zur .tar.xz-Datei',
        'themes_install_do':     '📦  Installieren',
        'themes_installing':     '⏳ Wird installiert…',
        'themes_install_ok':     '✅ Theme installiert: {names}',
        'themes_install_err':    '❌ Installation fehlgeschlagen: {error}',
        'themes_installed_in':   'Installiert in: {path}',
        'themes_activate_hint':  'Theme nach Installation hier aktivieren:',
        'themes_no_file':        '⚠️ Bitte zuerst eine Datei auswählen.',
        'yes':               'Ja',
        'no':                'Abbrechen',
        'toast_def_ok':      '✅ Standard gesetzt: {title}',
        'toast_def_err':     '❌ Fehler: {error}',
        'toast_timeout_ok':  '✅ Timeout: {t}s gesetzt',
        'toast_timeout_err': '❌ Fehler: {error}',
        'toast_theme_ok':    '✅ Theme aktiviert: {name}',
        'toast_restore_ok':  '✅ Backup wiederhergestellt!',
        'toast_restore_err': '❌ Fehler: {error}',
        'toast_saved':       '✅ Einstellungen gespeichert',
        'uefi':              'UEFI',
        'secure_boot':       'Secure Boot',
        'bls_boot':          'BLS-Boot',
        'grub_version':      'GRUB-Version',
        'backend_offline':   '⚠️ Backend nicht verbunden',
        'restart_hint':      'sudo systemctl start grub-pilot-backend',
    },
    'en': {
        'app_title':         'Grub Pilot',
        'nav_home':          '🏠  Home',
        'nav_entries':       '📋  Boot Entries',
        'nav_timeout':       '⏱️   Timeout',
        'nav_themes':        '🎨  Themes',
        'nav_backups':       '💾  Backups',
        'nav_settings':      '⚙️   Settings',
        'nav_help':          '❓  Help',
        'nav_about':         'ℹ️   About',
        'home_subtitle':     'Secure GRUB Configuration Tool',
        'entries_title':     '📋 Boot Entries',
        'entries_empty':     'No boot entries found.',
        'entries_set_def':   'Set Default',
        'timeout_title':     '⏱️ Boot Timeout',
        'timeout_disabled':  'Disabled',
        'timeout_instant':   'Instant',
        'timeout_sec':       '{n} seconds',
        'timeout_hint':      '-1 = no menu  |  0 = instant  |  1–30 = seconds',
        'timeout_save':      '💾  Save',
        'themes_title':      '🎨 GRUB Themes',
        'themes_empty':      'No themes installed.',
        'themes_hint':       'Themes are installed in /boot/grub/themes/.',
        'themes_activate':   'Activate',
        'backups_title':     '💾 Backups',
        'backups_empty':     'No backups available.',
        'backups_restore':   '↩  Restore',
        'backups_confirm':   'Really restore this backup?\nThe system will be reconfigured.',
        'settings_title':    '⚙️ Settings',
        'settings_lang':     'Language / Sprache',
        'settings_appear':   'Appearance',
        'settings_dark':     'Dark',
        'settings_light':    'Light',
        'settings_save':     '💾  Save Settings',
        'help_title':        '❓ Help & Documentation',
        'about_title':       'ℹ️ About Grub Pilot',
        'about_author':      'Author',
        'about_location':    'Location',
        'about_email':       'E-Mail',
        'about_license':     'License',
        'about_version':     'Version',
        'about_disclaimer':  ('⚠️ Disclaimer\n\n'
                              'This program is provided without any warranty. '
                              'Changes to the bootloader may render the system unbootable. '
                              'The author assumes no liability for data loss or system damage. '
                              'Use at your own risk.'),
        'about_thirdparty':  ('Third-party software used:\n'
                              '• customtkinter (MIT License)\n'
                              '  https://github.com/TomSchimansky/CustomTkinter\n'
                              '• dbus-python (LGPL-2.1)\n'
                              '  https://pypi.org/project/dbus-python/\n'
                              '• PyGObject (LGPL-2.1)\n'
                              '  https://pygobject.readthedocs.io/'),
        # Navigation
        'nav_section_main':  'CONFIGURATION',
        'nav_section_tools': 'TOOLS',
        'nav_kernel':        '⚙️   Kernel Parameters',
        'nav_wallpaper':     '🖼️   Wallpaper',
        'nav_display':       '🖥️   Display / Video',
        'nav_efi':           '🔒  EFI Boot Order',
        'nav_custom':        '📝  Custom Entries',
        'nav_profiles':      '📤  Profiles',
        'nav_logs':          '📄  Live Log',
        'nav_repair':        '🔧  Repair',
        # Kernel
        'kernel_title':      '⚙️ Kernel Parameters',
        'kernel_current':    'Current value (GRUB_CMDLINE_LINUX_DEFAULT)',
        'kernel_toggles':    'Quick Toggles',
        'kernel_save':       '💾  Save Parameters',
        'kernel_saved':      '✅ Kernel parameters saved',
        # Repair
        'repair_title':      '🔧 GRUB Repair',
        'repair_select_disk':'Select drive',
        'repair_refresh':    'Refresh',
        'repair_actions':    'Actions',
        'repair_install':    'Install GRUB',
        'repair_update':     'Update GRUB',
        'repair_warning':    '⚠️  Warning: grub-install writes the bootloader to the selected drive. Make sure you have selected the correct drive!',
        'repair_output':     'Output:',
        'repair_install_ok': '✅ GRUB installed successfully',
        'repair_update_ok':  '✅ GRUB updated successfully',
        'repair_no_disk':    '⚠️ Please select a drive',
        # Wallpaper
        'wallpaper_title':    '🖼️ Wallpaper',
        'wallpaper_select':   'Select image',
        'wallpaper_path_hint':'Path to image (PNG, JPG, TGA…)',
        'wallpaper_browse':   '📂  Select file…',
        'wallpaper_formats':  'Supported formats: PNG, JPG, TGA, BMP',
        'wallpaper_no_preview':'No image selected',
        'wallpaper_set':      '💾  Set image',
        'wallpaper_remove':   '🗑  Remove',
        'wallpaper_set_ok':   '✅ Wallpaper set',
        'wallpaper_removed':  '✅ Wallpaper removed',
        'wallpaper_no_file':  '⚠️ Please select a file first',
        # Display
        'display_title':          '🖥️ Display / Video Mode',
        'display_gfxmode':        'GRUB menu resolution',
        'display_gfxmode_hint':   'Recommended: auto or 1920x1080',
        'display_payload':        'Video mode after booting',
        'display_payload_text':   'Text mode',
        'display_payload_keep':   'Keep resolution',
        'display_payload_auto':   'Automatic',
        'display_payload_hint':   'keep = GRUB resolution is passed to the kernel',
        'display_osprober':       'os-prober (dual-boot detection)',
        'display_osprober_hint':  'Enable for dual-boot with Windows / other OS',
        'display_osprober_on':    'Enabled',
        'display_save':           '💾  Save settings',
        'display_saved':          '✅ Display settings saved',
        # EFI
        'efi_title':       '🔒 EFI Boot Order',
        'efi_refresh':     'Refresh',
        'efi_up':          'Up',
        'efi_down':        'Down',
        'efi_delete':      'Delete',
        'efi_save_order':  '💾  Save order',
        'efi_no_uefi':     'This system does not use UEFI. The EFI boot order is only available on UEFI systems.',
        'efi_empty':       'No EFI entries found.',
        'efi_deleted':     '✅ EFI entry deleted',
        'efi_order_saved': '✅ EFI boot order saved',
        # Custom Entries
        'custom_title':              '📝 Custom Boot Entries',
        'custom_hint':               'Edit /etc/grub.d/40_custom directly. GRUB is updated automatically after saving.',
        'custom_template':           '📄 Insert template',
        'custom_reload':             'Reload',
        'custom_save':               '💾  Save & update GRUB',
        'custom_saved':              '✅ Entries saved',
        'custom_reloaded':           '✅ Reloaded',
        'custom_empty_placeholder':  '# Add custom GRUB entries here\n# Use the template button as a starting point.\n',
        # Profiles
        'profiles_title':        '📤 Configuration Profiles',
        'profiles_export_title': 'Export configuration',
        'profiles_export_hint':  'Save current GRUB settings as a JSON profile',
        'profiles_export_btn':   'Export profile',
        'profiles_import_title': 'Import configuration',
        'profiles_import_hint':  'Load and apply a saved profile',
        'profiles_import_btn':   'Import profile',
        'profiles_current':      'Current configuration (preview)',
        'profiles_export_empty': '⚠️ No configuration found',
        'profiles_export_ok':    '✅ Profile exported: {path}',
        'profiles_import_ok':    '✅ Profile imported and GRUB updated',
        # Logs
        'logs_title':    '📄 Live Log Viewer',
        'logs_live_on':  'Start live',
        'logs_live_off': 'Stop live',
        'logs_clear':    'Clear',
        'logs_export':   'Export',
        'logs_filter':   'Filter:',
        'themes_install_btn':   '📦  Install Theme (.tar.xz)',
        'themes_install_title':  '📦 Install Theme from Archive',
        'themes_install_hint':   'Select GRUB theme archive (.tar.xz)',
        'themes_install_select': 'Select file…',
        'themes_install_path':   'Path to .tar.xz file',
        'themes_install_do':     '📦  Install',
        'themes_installing':     '⏳ Installing…',
        'themes_install_ok':     '✅ Theme installed: {names}',
        'themes_install_err':    '❌ Installation failed: {error}',
        'themes_installed_in':   'Installed in: {path}',
        'themes_activate_hint':  'Activate theme after installation:',
        'themes_no_file':        '⚠️ Please select a file first.',
        'yes':               'Yes',
        'no':                'Cancel',
        'toast_def_ok':      '✅ Default set: {title}',
        'toast_def_err':     '❌ Error: {error}',
        'toast_timeout_ok':  '✅ Timeout set: {t}s',
        'toast_timeout_err': '❌ Error: {error}',
        'toast_theme_ok':    '✅ Theme activated: {name}',
        'toast_restore_ok':  '✅ Backup restored!',
        'toast_restore_err': '❌ Error: {error}',
        'toast_saved':       '✅ Settings saved',
        'uefi':              'UEFI',
        'secure_boot':       'Secure Boot',
        'bls_boot':          'BLS Boot',
        'grub_version':      'GRUB Version',
        'backend_offline':   '⚠️ Backend not connected',
        'restart_hint':      'sudo systemctl start grub-pilot-backend',
    },
}

_lang = 'de'

def set_lang(lang: str):
    global _lang
    if lang in TRANSLATIONS:
        _lang = lang

def get_lang() -> str:
    return _lang

def t(key: str, **kwargs) -> str:
    text = TRANSLATIONS.get(_lang, TRANSLATIONS['de']).get(key, key)
    if kwargs:
        try:
            text = text.format(**kwargs)
        except Exception:
            pass
    return text
